[env:nologo_esp32c3_super_mini]
platform = espressif32
board = nologo_esp32c3_super_mini
framework = arduino
board_build.partitions = no_ota.csv

upload_port = COM9
monitor_port = COM9
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit Unified Sensor
    olikraus/U8g2
    h2zero/NimBLE-Arduino