[env:nologo_esp32c3_super_mini]
platform = espressif32
board = nologo_esp32c3_super_mini
framework = arduino
board_build.partitions = no_ota.csv

monitor_speed = 115200

lib_deps =
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit Unified Sensor
    greiman/SSD1306Ascii
    h2zero/NimBLE-Arduino